python run_experiments.py \
  --dataset pacs \
  --data_root data_root \
  --methods all \
  --backbones resnet50 \
  --seeds 0 1 2 \
  --epochs 30 \
  --holdout_fraction 0.2 \
  --scheduler none \
  --hparams_profile paper \
  --num_workers 4 \
  --save_dir outputs/paper30_r50 \
  --wandb \
  --wandb_project cv20252-pacs \
  --wandb_group pacs-resnet18-paper30 \
  --wandb_tags pacs resnet18 paper30 full \
  --skip_existing && \
python run_experiments.py \
  --dataset vlcs \
  --data_root data_root \
  --methods all \
  --backbones resnet50 \
  --seeds 0 1 2 \
  --epochs 30 \
  --holdout_fraction 0.2 \
  --scheduler none \
  --hparams_profile paper \
  --num_workers 4 \
  --save_dir outputs/paper30_r50 \
  --wandb \
  --wandb_project cv20252-vlcs \
  --wandb_group vlcs-resnet18-paper30 \
  --wandb_tags vlcs resnet18 paper30 full \
  --skip_existing && \
python run_experiments.py \
  --dataset office_home \
  --data_root data_root \
  --methods all \
  --backbones resnet50 \
  --seeds 0 1 2 \
  --epochs 30 \
  --holdout_fraction 0.2 \
  --scheduler none \
  --hparams_profile paper \
  --num_workers 4 \
  --save_dir outputs/paper30_r50 \
  --wandb \
  --wandb_project cv20252-office-home \
  --wandb_group office-home-resnet50-paper30 \
  --wandb_tags office_home resnet50 paper30 full \
  --skip_existing
python download_data.py --data_root data_root --datasets pacs vlcs office_home
